name: Python 3.9

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: test-hooks
      run: |
        python3 download.py amm-core-functionality https://github.com/gregtatcam/rippled.git
        RELEASE=True python3 bump.py rippled FAIL ./tools/rippled-amm-core-functionality